### PR TITLE
Add support for 1d column

### PR DESCRIPTION
**Pull request by tz-lom**
Capacity can receive tuple with extra dimensions, that change harmonize inerface with numpy and allso provides support for 1d ring buffer columns, like `RingBuffer((N, 1), dtype=int)`

### CODE REVIEW

**Comment by eric-wieser** [comment]
Thanks for the suggestion - but as you remark in the readme, you can already do exactly what you want with `RingBuffer(N, dtype=(int, 1))`.

I'd prefer not to introduce a new way to spell this - I quite deliberately wanted to separate the circular and non-circular axes by passing them in different places to the constructor.

**Comment by tz-lom** [comment]
Ok, I can understand that API design, but my PR was not only about it
check the following test:
```
r = RingBuffer(5, dtype=(np.int, 1))
		r.append(1)
		r.append(2)
		r.appendleft(3)
		self.assertEqual(np.shape(r), (3, 1))
		np.testing.assert_equal(r, np.array([[3], [1], [2]]))
```
for me it is not working
I've updated the code which keeps API unchanged but fixes that problem, can you check it?

**Comment by eric-wieser** [comment]
You're running into a numpy bug, which recently started giving a warning:
```
FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
```
Use `r = RingBuffer(5, dtype=(np.int, (1,)))` and your problem will go away.

**Comment by tz-lom** [comment]
I didn't know that, thank's for the hint

**Pull request closed without merging**
